### ISSUE TITLE
Inra Trait Variable Section- Context of use field content

### ISSUE THREAD

**Issue by teatree1212** [Brassica-Trait-Ontology/brato#2]
While the current content in the field "Context of use" (column E) in the TraitVariable Section is important information, I am not sure Crop Ontology is looking for that information in that field. I found  Context of use field- Specifications in their guidelines:

"If applicable, indicate the type of trials/research projects/models that this variable is generally observed. If there is more than one context of use, separate the entries by a coma ",""

But let's discuss this here?

**Comment by wjurkowski** [comment]
Indeed, it seems that currently the content is much more open that what the specification suggest. Perhaps we could have additional 'comments' column? Could we run through examples of the content of this field in the CO to see how much the brato content diverged?
