### ISSUE TITLE
Commit naming conventions

### ISSUE THREAD

**Issue by teatree1212** [Brassica-Trait-Ontology/brato#3]
I was thinking that maybe we should have a "mini commit ontology" within this Ontology making process, to be more clear with our commits. For important commits, I suggest having some standard words at the beginning of our message  e.g.

[institute name ] -> [Earlham Institute] [Inra] [Southern Cross]
and some small info on what is done, I found that I needed these two already

[add traits] [update] etc. (  you suggest)

followed by any free text description of what you did . Here an example commit from myself:

git commit -m "[Earlham Institute] [add traits] next batch of RIPR traits"
git commit -m "[Earlham Institute] [update] method and Scale IDs"

What do you think? Overkill or something you would agree with and would be willing to adapt?

**Comment by sodurand** [comment]
I'm OK with your proposition.

**Comment by wjurkowski** [comment]
I'm ok with it as long as you find it helpful, but let's keep it simple. Most importantly the description should be concise and informative

**Comment by abaten** [comment]
Fine with me as well.

**Comment by teatree1212** [comment]
okay, since one person of each Institution agrees, I will close this issue and add it to the readme.
