### ISSUE TITLE
4 scale IDs are missing

### ISSUE THREAD

**Issue by sodurand** [Brassica-Trait-Ontology/brato#6]
It's recommended to have a scale ID for each trait. Otherwise, the CropOntology system will generate automatically a new scale ID. This ID can be taken from https://www.ebi.ac.uk/ols/ontologies/uo, from existing scale ID in our ontology, or can be a new one, according to the naming convention.

**Comment by wjurkowski** [comment]
I added some new IDs and corrected some others (replaced ours with UO ids)
